View all grades
helen-choi/sgt-react pull request #1
Opened 2020-04-18 08:16 UTC by helen-choi

<img width="1580" alt="Screen Shot 2020-04-18 at 1 15 09 AM" src="https://user-images.githubusercontent.com/5043311/79632140-3e218500-8112-11ea-9508-4691e4436a2c.png">

2020-04-18 14:23 UTC, thebearingedge requested changes

2020-04-18 14:23 UTC, thebearingedge commented on server/public/styles.css
> +}
Bootstrap already defines a `container` class. But it also defines some flex helpers. See if you can use those to reduce the amount of custom CSS required.

https://getbootstrap.com/docs/4.4/utilities/flex/

2020-04-18 14:23 UTC, thebearingedge commented on server/public/index.html
> +    </div>
You can remove these things since React will erase them anyway.

2020-04-18 14:23 UTC, thebearingedge commented on server/public/index.html
> +  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
Bootstrap is already linked for you.

2020-04-18 14:23 UTC, thebearingedge commented on server/public/index.html
> +  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="
Bootstrap is already linked for you.

2020-04-19 04:40 UTC, thebearingedge requested changes

2020-04-19 04:40 UTC, thebearingedge commented on server/public/styles.css
> +} */
Please do not turn in commented out code 😢

2020-04-19 04:41 UTC, helen-choi commented on server/public/styles.css
> +} */
Oops! I meant to delete :)

2020-04-19 04:43 UTC, merged